name: AEM Maven Build

on:
  workflow_call:
    inputs:
      java-version:
        description: Major Java SDK version
        required: true
        default: 11
        type: number

jobs:
  build:
    name: AEM Maven Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ inputs.java-version }}
          cache: maven

      - name: Maven build
        run: mvn --batch-mode --update-snapshots install

      - name: Upload AEM content packages
        uses: actions/upload-artifact@v4
        with:
          name: aem-content-packages
          path: "*/target/*.zip"
