name: AEM Maven Build

on:
  workflow_call:

jobs:
  build:
    name: AEM Maven Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
          cache: maven

      - name: Maven build
        run: mvn --batch-mode --update-snapshots install
