name: GitHub Release

on:
  workflow_call:
    inputs:
      version:
        description: Version
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update CHANGELOG.md
        uses: thomaseizinger/keep-a-changelog-new-release@v3
        with:
          tag: ${{ inputs.version }}

      - name: Query release info
        id: query-release-info
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: query
          version: latest

      - name: Commit and push release
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Create release ${{ steps.query-release-info.outputs.version }}"
          tagging_message: ${{ steps.query-release-info.outputs.version }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.update-query-release-info.outputs.version }}
          tag_name: ${{ steps.query-release-info.outputs.version }}
          body: ${{ steps.query-release-info.outputs.release-notes }}
