name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
        type: string

jobs:
  call-workflow:
    uses: orbinson/workflows/.github/workflows/github-release.yml@main
    with:
      version: ${{ inputs.version }}
